name: app-neurobase

services:
  nbase:
    image: nbase:1.0
    container_name: app-neurobase
    ports:
      - "${NEO4J_PORT_HTTP}:7474"
      - "${NEO4J_PORT_BOLT}:7687"
    environment:
      NEO4J_AUTH: "neo4j/${NEO4J_PASSWORD}"